apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-lib
  title: Test library
  description: Test library description
  tags:
    - test
    - spring-boot
    - java
    - maven
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: group:default/libraries
  lifecycle: experimental

