site_name: "mirai-lib-backgroundable"
site_description: "This library provides configuration and annotations to run methods the background. Use this library if you need to run methods in the background."
nav:
  - Intro: index.md
  - FAQ: faq.md
plugins:
  - techdocs-core